news_homepage:
    pattern:  /tsi/news/{name}
    defaults: { _controller: NewsBundle:Default:index }

news_add:
    pattern:  /tsi/news/add
    defaults: { _controller: NewsBundle:Default:add }

news_edit:
    pattern:  /tsi/news/edit
    defaults: { _controller: NewsBundle:Default:edit }

news_delete:
    pattern:  /tsi/news/delete
    defaults: { _controller: NewsBundle:Default:delete }
